### ISSUE TITLE
Crystal 0.35.0 Breaks

### ISSUE THREAD

**Issue by AndiLavera** [imdrasil/sam.cr#13]
What I am doing:
`crystal sam.cr -- help`

Expected Behavior:
It should print the help message
```
Tasks:
-------------------:--------------------
help                  Prints description for all tasks
generate:makefile     Generates makefile extension. Now command could be executed via `make sam your:command argument`
```

Whats actually happening:

```
lib/sam/src/sam.cr:41:5 in 'invoke'
lib/sam/src/sam.cr:77:7 in 'process_tasks'
lib/sam/src/sam.cr:56:7 in 'help'
sam.cr:9:1 in '__crystal_main'
../../../.crenv/versions/0.35.0/share/crystal/src/crystal/main.cr:105:5 in 'main_user_code'
../../../.crenv/versions/0.35.0/share/crystal/src/crystal/main.cr:91:7 in 'main'
../../../.crenv/versions/0.35.0/share/crystal/src/crystal/main.cr:114:3 in 'main'
__libc_start_main
_start
???
Task -- was not found
```

Other info:
I use crenv. I noticed my projects sam file begin to bug out on 0.35.0. On the same sam.cr file, switching between 0.34.0 and 0.35.0 causes the break to occur. This can be tested with the default sam file:

```crystal
require "sam"
Sam.help
# Ran with `crystal sam.cr -- help`
```

I also cloned the sam.cr repo and tested the specs. Same broken functionality on 0.35.0 when running `crystal examples/sam.cr -- setup`. The setup command fixes immediately when crenv is set to 0.34.0 and all specs pass.

**Comment by imdrasil** [comment]
it's very likely because of new argument parsing logic in recent crystal version. try to run `crystal sam.cr help`. Will have a look and update project.

**Comment by AndiLavera** [comment]
Thanks for the quick fix! 

I did want to ask, why the `--`? Why not `sam db:migrate`?

Edit: Oh did we get rid of it in the newest version? :)

**Comment by imdrasil** [comment]
the `--` was required to console utility (`crystal run`) to pass given arguments to compiled program instead of itself. But in the latest version they changed behavior and now options are passed automatically
