### ISSUE TITLE
Unwanted sam.cr file

### ISSUE THREAD

**Issue by gdotdesign** [imdrasil/sam.cr#9]
Hey,

I'm using Jennifer as an ORM and lately when I install dependencies a `sam.cr` file is created in root of the project.

Since I'm not using `sam` directly it's kind of annoying to have the file deleted every time and I know I can add it `.gitignore` to not to have it in the repository but still the file is there.

Is there any way I can prevent it from generating? I know this is for the new uses but I whish we could remove this after install part.

Thanks!

**Comment by imdrasil** [comment]
hm, it really may be annoying. I should think about this. Also could you please describe what do you mean "directly"? And do you use Jennifer's migration mechanism?

**Comment by gdotdesign** [comment]
>  Also could you please describe what do you mean "directly"?

I only have `jennifer` as a dependency in `shard.yml` and since it depends on `sam.cr` it gets installed so it's an indirect dependency.

> And do you use Jennifer's migration mechanism?

I call the `Jennifer::Migration::Runner.migrate` and `Jennifer::Migration::Runner.rollback` in a CLI of the application I'm developing.

**Comment by imdrasil** [comment]
Sorry - forget to update this thread. Sam now is optional for Jennifer
